package com.example.greeting.service;

import com.aimp.annotations.AIImplemented;
import jakarta.validation.Valid;
import org.springframework.stereotype.Service;
import org.springframework.validation.annotation.Validated;

/**
 * Spring service contract whose implementation is generated by AIMP at compile time.
 */
@AIImplemented
@Service
@Validated
public interface GreetingService {
    /**
     * Creates a localized greeting response.
     * Supports at least {@code en}, {@code ro}, and {@code es}.
     * Uses {@code request.name()} exactly as provided.
     * Produces a response message like {@code Hello, Ion!}, {@code Salut, Ion!},
     * or {@code Hola, Ion!} and appends an extra {@code !} when
     * {@code request.excited()} is true.
     *
     * @param request greeting request payload
     * @return generated greeting response
     */
    GreetingResponse greet(@Valid GreetingRequest request);
}
