package com.example.greeting.service;

import com.aimp.annotations.AIImplemented;
import jakarta.validation.Valid;
import java.util.Locale;
import org.springframework.stereotype.Service;
import org.springframework.validation.annotation.Validated;

/**
 * Spring service contract whose implementation is generated by AIMP at compile time.
 */
@AIImplemented
@Service
@Validated
public abstract class GreetingService {
    /**
     * Creates the greeting service contract.
     */
    protected GreetingService() {
    }

    /**
     * Normalizes the requested language and falls back to English when the
     * caller does not provide a supported value.
     *
     * @param requestedLanguage caller language preference
     * @return normalized language code
     */
    protected String normalizeLanguage(String requestedLanguage) {
        if (requestedLanguage == null || requestedLanguage.isBlank()) {
            return "en";
        }

        String normalized = requestedLanguage.toLowerCase(Locale.ROOT);
        return switch (normalized) {
            case "ro", "es" -> normalized;
            default -> "en";
        };
    }

    /**
     * Returns a default signature label for the chosen language.
     *
     * @param language normalized language code
     * @return localized team signature
     */
    protected String defaultSignature(String language) {
        return switch (language) {
            case "ro" -> "Echipa de suport";
            case "es" -> "Equipo de soporte";
            default -> "Support Team";
        };
    }

    /**
     * Creates a localized greeting response.
     * Welcome greetings should feel warm, birthday greetings should feel
     * celebratory, and farewell greetings should feel polite and clear.
     * Formal greetings should sound more professional than friendly ones.
     * VIP callers should be acknowledged as valued guests.
     * When a sign-off is requested, use the provided sender name when present;
     * otherwise use the default team signature for the chosen language.
     * Unsupported languages should fall back to English.
     *
     * @param request greeting request payload
     * @return generated greeting response
     */
    public abstract GreetingResponse greet(@Valid GreetingRequest request);
}
