package com.example.greeting.service;

import com.aimp.annotations.AIContract;
import com.aimp.annotations.AIImplemented;
import jakarta.validation.Valid;
import org.springframework.stereotype.Service;
import org.springframework.validation.annotation.Validated;

/**
 * Spring service contract whose implementation is generated by AIMP at compile time.
 */
@Service
@Validated
@AIContract(version = "1")
public interface GreetingService {
    /**
     * Creates a localized greeting response.
     *
     * @param request greeting request payload
     * @return generated greeting response
     */
    @AIImplemented("""
        Create a greeting response for the incoming request.
        Use request.name exactly as provided.
        Normalize request.language to lower case.
        If the language is ro, use Salut, <name>!.
        If the language is es, use Hola, <name>!.
        Otherwise use Hello, <name>!.
        If request.excited() is true, replace the final ! with !!.
        Return new com.example.greeting.service.GreetingResponse(message, normalizedLanguage).
        Do not call external systems or generate random data.
        """)
    GreetingResponse greet(@Valid GreetingRequest request);
}
