package com.example.greeting.api;

import com.aimp.annotations.AIImplemented;
import com.example.greeting.service.GreetingRequest;
import com.example.greeting.service.GreetingResponse;
import com.example.greeting.service.GreetingService;
import jakarta.validation.Valid;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * HTTP entry point for the Spring Boot greeting example.
 */
@AIImplemented
@RestController
@RequestMapping("/api/greetings")
public abstract class GreetingController {
    /**
     * Injected greeting service used by generated controller implementations.
     */
    protected final GreetingService greetingService;

    /**
     * Creates the controller with the generated greeting service bean.
     *
     * @param greetingService service generated by AIMP and discovered by Spring
     */
    public GreetingController(GreetingService greetingService) {
        this.greetingService = greetingService;
    }

    /**
     * Creates a greeting response from the request payload by delegating directly
     * to {@link #greetingService} and returning its result.
     * The generated override should preserve the Spring MVC and validation
     * annotations required for request handling.
     *
     * @param request greeting request payload
     * @return resolved greeting response
     */
    @PostMapping
    public abstract GreetingResponse greet(@Valid @RequestBody GreetingRequest request);
}
