package com.example.greeting.api;

import com.example.greeting.service.GreetingRequest;
import com.example.greeting.service.GreetingResponse;
import com.example.greeting.service.GreetingService;
import jakarta.validation.Valid;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * HTTP entry point for the Spring Boot greeting example.
 */
@RestController
@RequestMapping("/api/greetings")
public class GreetingController {
    private final GreetingService greetingService;

    /**
     * Creates the controller with the generated greeting service bean.
     *
     * @param greetingService service generated by AIMP and discovered by Spring
     */
    public GreetingController(GreetingService greetingService) {
        this.greetingService = greetingService;
    }

    /**
     * Creates a greeting response from the request payload.
     *
     * @param request greeting request payload
     * @return resolved greeting response
     */
    @PostMapping
    public GreetingResponse greet(@Valid @RequestBody GreetingRequest request) {
        return greetingService.greet(request);
    }
}
