package com.aimp.annotations;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks an abstract contract method whose implementation should be generated by
 * AIMP.
 */
@Documented
@Target(ElementType.METHOD)
@Retention(RetentionPolicy.SOURCE)
public @interface AIImplemented {
    /**
     * Returns the handwritten implementation intent for the annotated method.
     *
     * @return the method implementation description
     */
    String value();
}
